package org.ekbana.minikafka.client.common;

public enum RequestType {
    NEW_CONNECTION,
    AUTH,
    TOPIC_CREATE,TOPIC_DELETE,
    PRODUCER_CONFIG, PRODUCER_RECORD_WRITE,
    CONSUMER_CONFIG,CONSUMER_RECORD_READ,CONSUMER_OFFSET_COMMIT
}
