package org.ekbana.server.v2.client;

public enum KafkaClientState {
    NEW,
    CONNECTING,CONNECTED,
    AUTHENTICATING,AUTHENTICATED,
    CONFIGURING_PRODUCER,CONFIGURED_PRODUCER,
    CONFIGURING_CONSUMER,CONFIGURED_CONSUMER,
    CREATING_TOPIC,CREATED_TOPIC,
    DELETING_TOPIC,DELETED_TOPIC,
    CLOSING,CLOSE,CLOSED
}
